In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

tf.__version__

'2.1.0'

# 당뇨병을 진단해봅시다.

0:-100 첫줄부터 아래에서 100번째까지
0:-1 왼쪽에서 오른쪽끝에서 2번째까지
[-1] 오른쪽 마지막만
-100: 아래에서 100번째부터 마지막까지


In [2]:
xy = np.loadtxt('./dataset_392.csv', delimiter=',', dtype=np.float32)
x_train = xy[0:500, 0:3]
y_train = xy[0:500, [3]]

x_test = xy[500:506, 0:3]
y_test = xy[500:506, [3]]

print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(500, 3) (500, 1)
(6, 3) (6, 1)


In [3]:
print(x_test)
print(y_test)

[[1.5864828e-01 8.1448275e-01 1.7477594e-01]
 [0.0000000e+00 1.0000000e+00 2.9899999e-23]
 [0.0000000e+00 1.0000000e+00 1.1500000e-37]
 [0.0000000e+00 1.0000000e+00 1.1500000e-37]
 [0.0000000e+00 1.0000000e+00 1.1500000e-37]
 [0.0000000e+00 1.0000000e+00 1.1500000e-37]]
[[-1.0388241e+01]
 [-1.4974511e+00]
 [-1.5226110e-02]
 [ 4.9998090e-03]
 [ 4.0219938e-03]
 [-3.6868080e-03]]


In [4]:
dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train)).batch(len(x_train))


In [5]:
W = tf.Variable(tf.random.normal([3, 1]), name='weight')
b = tf.Variable(tf.random.normal([1]), name='bias')


## 가설 설정
* 병이 있다 / 없다로 분류
* softmax classification으로 진행

## $$ y_k = \frac{exp(x_k)}{\sum_{i=1}^{n}exp(x_i)}  $$

In [6]:
def logistic_regression(features):
    hypothesis  = tf.divide(1., 1. + tf.exp(-(tf.matmul(features, W) + b)))
    return hypothesis
  
print(logistic_regression(x_train))

tf.Tensor(
[[0.29177463]
 [0.29183984]
 [0.29019257]
 [0.29149744]
 [0.29603162]
 [0.30273467]
 [0.30595443]
 [0.310732  ]
 [0.30287227]
 [0.3006418 ]
 [0.30204904]
 [0.29943538]
 [0.2999595 ]
 [0.29940778]
 [0.31018123]
 [0.2928293 ]
 [0.302822  ]
 [0.29923177]
 [0.28793   ]
 [0.28082028]
 [0.3057923 ]
 [0.28628013]
 [0.27944738]
 [0.30283627]
 [0.30346242]
 [0.29888678]
 [0.3012154 ]
 [0.3105539 ]
 [0.3143606 ]
 [0.3045667 ]
 [0.30100214]
 [0.30036896]
 [0.30293128]
 [0.30781534]
 [0.30634508]
 [0.30815762]
 [0.3078053 ]
 [0.30418918]
 [0.30566925]
 [0.3021837 ]
 [0.299178  ]
 [0.28541666]
 [0.293687  ]
 [0.29345113]
 [0.3050837 ]
 [0.3007962 ]
 [0.30559945]
 [0.30139485]
 [0.30277622]
 [0.3071143 ]
 [0.30792102]
 [0.3020735 ]
 [0.31094402]
 [0.30437216]
 [0.2926201 ]
 [0.30533257]
 [0.30534083]
 [0.3082116 ]
 [0.30299014]
 [0.28505093]
 [0.30394706]
 [0.30764106]
 [0.3063591 ]
 [0.31272137]
 [0.30825227]
 [0.30853003]
 [0.3051138 ]
 [0.30522972]
 [0.30658162]
 [0.2892731 ]
 [0.29350

## Loss Function

* 기존 MSE 대신 Cross Entropy 사용

## $$
\begin{align}
loss(h(x),y) & = −y log(h(x))−(1−y)log(1−h(x))
\end{align}
$$

In [15]:
def loss_fn(hypothesis, labels):
    loss = -tf.reduce_mean(labels * tf.math.log(hypothesis) + \
                           (1 - labels) * tf.math.log(1 - hypothesis))
    return loss

optimizer = tf.compat.v1.train.GradientDescentOptimizer(learning_rate=0.001)

## 학습

In [16]:
epochs = 5000

for step in range(epochs):
  for features, labels in dataset:
    with tf.GradientTape() as tape:
      loss_value = loss_fn(logistic_regression(features),labels)
      grads = tape.gradient(loss_value, [W,b])
      optimizer.apply_gradients(grads_and_vars=zip(grads,[W,b]))
      if step % 100 == 0:
            print("Iter: {}, Loss: {:.4f}".format(step, loss_fn(logistic_regression(features),labels)))

Iter: 0, Loss: -19.3960
Iter: 100, Loss: -19.4926
Iter: 200, Loss: -19.5892
Iter: 300, Loss: -19.6858
Iter: 400, Loss: -19.7824
Iter: 500, Loss: -19.8790
Iter: 600, Loss: -19.9756
Iter: 700, Loss: -20.0722
Iter: 800, Loss: -20.1688
Iter: 900, Loss: -20.2654
Iter: 1000, Loss: -20.3620
Iter: 1100, Loss: -20.4586
Iter: 1200, Loss: -20.5552
Iter: 1300, Loss: -20.6518
Iter: 1400, Loss: -20.7484
Iter: 1500, Loss: -20.8449
Iter: 1600, Loss: -20.9415
Iter: 1700, Loss: -21.0381
Iter: 1800, Loss: -21.1346
Iter: 1900, Loss: -21.2311
Iter: 2000, Loss: -21.3276
Iter: 2100, Loss: -21.4241
Iter: 2200, Loss: -21.5207
Iter: 2300, Loss: -21.6172
Iter: 2400, Loss: -21.7137
Iter: 2500, Loss: -21.8102
Iter: 2600, Loss: -21.9067
Iter: 2700, Loss: -22.0032
Iter: 2800, Loss: -22.0997
Iter: 2900, Loss: -22.1962
Iter: 3000, Loss: -22.2927
Iter: 3100, Loss: -22.3891
Iter: 3200, Loss: -22.4856
Iter: 3300, Loss: -22.5821
Iter: 3400, Loss: -22.6786
Iter: 3500, Loss: -22.7750
Iter: 3600, Loss: -22.8715
Iter: 3700, L

## 테스트

In [17]:
def accuracy_fn(hypothesis, labels):
    predicted = tf.cast(hypothesis > 0.5, dtype=tf.int32)
    accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, labels), dtype=tf.float32))
    return accuracy

In [18]:
test_acc = accuracy_fn(logistic_regression(x_test),y_test)
print("Testset Accuracy: {:.4f}".format(test_acc))

Testset Accuracy: 0.6667
