In [1]:
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.utils import to_categorical
##from keras.datasets import mnist

Using TensorFlow backend.


In [2]:
import numpy as np

In [3]:
x1 = np.loadtxt('./X_train_short.txt')
x2 = np.loadtxt('./X_test_short.txt')
y_train = np.loadtxt('./y_train_short.txt')
y_test = np.loadtxt('./y_test_short.txt')
## user_id, pc_throttle, pc_brake, pc_steering, pc_speed, pc_lap_distance
X_train = x1.reshape(9615, 3)
X_test = x2.reshape(5685, 3)
print(str(X_train.shape))
print(str(X_test.shape))

(9615, 3)
(5685, 3)


가속값, 속도, 위치 : 3가지로 구성된 배열로 학습 데이터는 9615, 테스트 데이터는 5685개의 데이터를 사용

In [4]:
print("train data (count, row, column) : " + str(X_train.shape) )
print("test data  (count, row, column) : " + str(X_test.shape) )

train data (count, row, column) : (9615, 3)
test data  (count, row, column) : (5685, 3)


학습 데이터의 하나를 샘플로 확인

In [5]:
input_dim = 3 
X_train = X_train.reshape(9615, input_dim) 
X_test = X_test.reshape(5685, input_dim)

In [6]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(9615, 3)
(9615,)
(5685, 3)
(5685,)


학습 시, y값과의 cross entropy를 측정해야하므로, 아래의 코드를 실행하여 y를 one hot encoding으로 변환

In [7]:
num_classes = 11
y_train = to_categorical(y_train, num_classes)
y_test = to_categorical(y_test, num_classes)

one hot encoding으로 변환되어 클래스 갯수만큼의 길이를 갖는 벡터로 변경이 되었고 해당되는 인덱스의 값 확인

In [8]:
print(y_train[0])
print(y_test[0])

[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]


케라스의 Sequential()을 사용하여 소프트맥스를 구현

In [9]:
model = Sequential() 
model.add(Dense(input_dim=input_dim, units = 11, activation='softmax'))

categorical_crossentropy를 비용함수로 사용한 경사하강법으로 최적의 W와 biases를 학습

In [10]:
model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy']) 
model.fit(X_train, y_train, batch_size=2048, epochs=100, verbose=0)

테스트를 진행하여, 정확도를 측정

In [11]:
score = model.evaluate(X_test, y_test) 
print('Test accuracy:', score[1])

5685/5685 [==============================] - 0s 32us/step
Test accuracy: 1.0


아래의 코드를 실행하여, 소프트맥스 모델의 구조를 시각화

In [12]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 11)                44        
Total params: 44
Trainable params: 44
Non-trainable params: 0
_________________________________________________________________


In [13]:
model.layers[0].weights

[<tf.Variable 'dense_1/kernel:0' shape=(3, 11) dtype=float32, numpy=
 array([[ 0.32240763,  1.1714277 ,  0.6163991 , -0.51117015, -0.23661518,
         -0.62441605, -0.01772034,  0.12216317, -0.16181448,  0.00657001,
          0.25204355],
        [-0.38675737,  0.39523473,  0.7685545 , -0.3806363 ,  0.05803515,
         -0.3039265 ,  0.47325137,  0.41701362,  0.42980823, -0.652497  ,
          0.10807973],
        [-0.5165611 , -0.12499576,  0.45170614, -0.16056992, -0.19228114,
         -0.3779385 , -0.38675562, -0.13070019, -0.431252  , -0.4059472 ,
         -0.35870314]], dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(11,) dtype=float32, numpy=
 array([-0.29557613,  0.66591567,  1.4323374 , -0.16496147,  0.08245485,
        -0.14027579, -0.32803193, -0.40103605, -0.27883717, -0.21264766,
        -0.3593419 ], dtype=float32)>]